/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Users/heshiyu/.config/yarn/global/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-aa24dce8",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-aa24dce8").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-3fe5aafc",
    path: "/output/fruit/component-lib/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3fe5aafc").then(next)
    },
  },
  {
    path: "/output/fruit/component-lib/index.html",
    redirect: "/output/fruit/component-lib/"
  },
  {
    name: "v-5b53c4e4",
    path: "/output/fruit/template/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5b53c4e4").then(next)
    },
  },
  {
    path: "/output/fruit/template/index.html",
    redirect: "/output/fruit/template/"
  },
  {
    name: "v-5f749ca8",
    path: "/output/standard/css/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5f749ca8").then(next)
    },
  },
  {
    path: "/output/standard/css/index.html",
    redirect: "/output/standard/css/"
  },
  {
    name: "v-1adb505c",
    path: "/output/standard/eslint/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1adb505c").then(next)
    },
  },
  {
    path: "/output/standard/eslint/index.html",
    redirect: "/output/standard/eslint/"
  },
  {
    name: "v-6289560e",
    path: "/output/standard/git/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6289560e").then(next)
    },
  },
  {
    path: "/output/standard/git/index.html",
    redirect: "/output/standard/git/"
  },
  {
    name: "v-e8005c80",
    path: "/output/standard/interface/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e8005c80").then(next)
    },
  },
  {
    path: "/output/standard/interface/index.html",
    redirect: "/output/standard/interface/"
  },
  {
    name: "v-6aaba45c",
    path: "/output/standard/js/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6aaba45c").then(next)
    },
  },
  {
    path: "/output/standard/js/index.html",
    redirect: "/output/standard/js/"
  },
  {
    name: "v-3ccafbec",
    path: "/output/standard/stylelint/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3ccafbec").then(next)
    },
  },
  {
    path: "/output/standard/stylelint/index.html",
    redirect: "/output/standard/stylelint/"
  },
  {
    name: "v-fa442548",
    path: "/overview/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fa442548").then(next)
    },
  },
  {
    path: "/overview/index.html",
    redirect: "/overview/"
  },
  {
    name: "v-ad67a4f0",
    path: "/skill/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ad67a4f0").then(next)
    },
  },
  {
    path: "/skill/index.html",
    redirect: "/skill/"
  },
  {
    name: "v-388a9f70",
    path: "/skill/algorithm/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-388a9f70").then(next)
    },
  },
  {
    path: "/skill/algorithm/index.html",
    redirect: "/skill/algorithm/"
  },
  {
    name: "v-c3f1c76c",
    path: "/skill/algorithm/basic/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c3f1c76c").then(next)
    },
  },
  {
    path: "/skill/algorithm/basic/index.html",
    redirect: "/skill/algorithm/basic/"
  },
  {
    name: "v-5378dd17",
    path: "/skill/algorithm/dp/0053-maximum-sum-subarray.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5378dd17").then(next)
    },
  },
  {
    name: "v-7ad3f83d",
    path: "/skill/algorithm/dp/0198-house-robber.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ad3f83d").then(next)
    },
  },
  {
    name: "v-0916e188",
    path: "/skill/algorithm/dp/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0916e188").then(next)
    },
  },
  {
    path: "/skill/algorithm/dp/index.html",
    redirect: "/skill/algorithm/dp/"
  },
  {
    name: "v-5e6e023c",
    path: "/skill/algorithm/leetcode/46-permutations/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5e6e023c").then(next)
    },
  },
  {
    path: "/skill/algorithm/leetcode/46-permutations/index.html",
    redirect: "/skill/algorithm/leetcode/46-permutations/"
  },
  {
    name: "v-1677139c",
    path: "/skill/algorithm/leetcode/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1677139c").then(next)
    },
  },
  {
    path: "/skill/algorithm/leetcode/index.html",
    redirect: "/skill/algorithm/leetcode/"
  },
  {
    name: "v-f3efa388",
    path: "/skill/algorithm/search/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f3efa388").then(next)
    },
  },
  {
    path: "/skill/algorithm/search/index.html",
    redirect: "/skill/algorithm/search/"
  },
  {
    name: "v-c4d39122",
    path: "/skill/algorithm/sort/Bubble.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c4d39122").then(next)
    },
  },
  {
    name: "v-49cd7faf",
    path: "/skill/algorithm/sort/Heap.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-49cd7faf").then(next)
    },
  },
  {
    name: "v-0cc5a943",
    path: "/skill/algorithm/sort/Insertion.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0cc5a943").then(next)
    },
  },
  {
    name: "v-56ba5331",
    path: "/skill/algorithm/sort/Merge.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-56ba5331").then(next)
    },
  },
  {
    name: "v-31475672",
    path: "/skill/algorithm/sort/Quick.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-31475672").then(next)
    },
  },
  {
    name: "v-330152bc",
    path: "/skill/algorithm/sort/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-330152bc").then(next)
    },
  },
  {
    path: "/skill/algorithm/sort/index.html",
    redirect: "/skill/algorithm/sort/"
  },
  {
    name: "v-a7e400ce",
    path: "/skill/algorithm/sort/Radix.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a7e400ce").then(next)
    },
  },
  {
    name: "v-cda9d1ee",
    path: "/skill/algorithm/sort/Selection.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cda9d1ee").then(next)
    },
  },
  {
    name: "v-c06f517e",
    path: "/skill/algorithm/sort/Shell.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c06f517e").then(next)
    },
  },
  {
    name: "v-81ddf62c",
    path: "/skill/algorithm/time-complexity/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-81ddf62c").then(next)
    },
  },
  {
    path: "/skill/algorithm/time-complexity/index.html",
    redirect: "/skill/algorithm/time-complexity/"
  },
  {
    name: "v-ea2c57a4",
    path: "/skill/computeracy/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ea2c57a4").then(next)
    },
  },
  {
    path: "/skill/computeracy/index.html",
    redirect: "/skill/computeracy/"
  },
  {
    name: "v-61ac20c0",
    path: "/skill/css/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-61ac20c0").then(next)
    },
  },
  {
    path: "/skill/css/index.html",
    redirect: "/skill/css/"
  },
  {
    name: "v-c926a218",
    path: "/skill/computeracy/scheduling-strategy/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c926a218").then(next)
    },
  },
  {
    path: "/skill/computeracy/scheduling-strategy/index.html",
    redirect: "/skill/computeracy/scheduling-strategy/"
  },
  {
    name: "v-6ccc4100",
    path: "/skill/css/bfc/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6ccc4100").then(next)
    },
  },
  {
    path: "/skill/css/bfc/index.html",
    redirect: "/skill/css/bfc/"
  },
  {
    name: "v-ebad3048",
    path: "/skill/css/flex-box/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ebad3048").then(next)
    },
  },
  {
    path: "/skill/css/flex-box/index.html",
    redirect: "/skill/css/flex-box/"
  },
  {
    name: "v-7da2d788",
    path: "/skill/css/layout/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7da2d788").then(next)
    },
  },
  {
    path: "/skill/css/layout/index.html",
    redirect: "/skill/css/layout/"
  },
  {
    name: "v-6e825af6",
    path: "/skill/css/media/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e825af6").then(next)
    },
  },
  {
    path: "/skill/css/media/index.html",
    redirect: "/skill/css/media/"
  },
  {
    name: "v-6863a87c",
    path: "/skill/css/px/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6863a87c").then(next)
    },
  },
  {
    path: "/skill/css/px/index.html",
    redirect: "/skill/css/px/"
  },
  {
    name: "v-2756708e",
    path: "/skill/css/sass-less/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2756708e").then(next)
    },
  },
  {
    path: "/skill/css/sass-less/index.html",
    redirect: "/skill/css/sass-less/"
  },
  {
    name: "v-d9c07e48",
    path: "/skill/html/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d9c07e48").then(next)
    },
  },
  {
    path: "/skill/html/index.html",
    redirect: "/skill/html/"
  },
  {
    name: "v-46a9f408",
    path: "/skill/html/other/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-46a9f408").then(next)
    },
  },
  {
    path: "/skill/html/other/index.html",
    redirect: "/skill/html/other/"
  },
  {
    name: "v-5a20ceb0",
    path: "/skill/html/web-worker/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5a20ceb0").then(next)
    },
  },
  {
    path: "/skill/html/web-worker/index.html",
    redirect: "/skill/html/web-worker/"
  },
  {
    name: "v-44fc8acf",
    path: "/skill/js/AMDCMD.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-44fc8acf").then(next)
    },
  },
  {
    name: "v-27efc41c",
    path: "/skill/js/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-27efc41c").then(next)
    },
  },
  {
    path: "/skill/js/index.html",
    redirect: "/skill/js/"
  },
  {
    name: "v-e924dc08",
    path: "/skill/js/class/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e924dc08").then(next)
    },
  },
  {
    path: "/skill/js/class/index.html",
    redirect: "/skill/js/class/"
  },
  {
    name: "v-821d2208",
    path: "/skill/js/design-patterns/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-821d2208").then(next)
    },
  },
  {
    path: "/skill/js/design-patterns/index.html",
    redirect: "/skill/js/design-patterns/"
  },
  {
    name: "v-1217ad7c",
    path: "/skill/js/dom/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1217ad7c").then(next)
    },
  },
  {
    path: "/skill/js/dom/index.html",
    redirect: "/skill/js/dom/"
  },
  {
    name: "v-3dfbe72c",
    path: "/skill/js/event-loop/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3dfbe72c").then(next)
    },
  },
  {
    path: "/skill/js/event-loop/index.html",
    redirect: "/skill/js/event-loop/"
  },
  {
    name: "v-5fa5c4fc",
    path: "/skill/js/modular/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5fa5c4fc").then(next)
    },
  },
  {
    path: "/skill/js/modular/index.html",
    redirect: "/skill/js/modular/"
  },
  {
    name: "v-76d111c8",
    path: "/skill/js/regex/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-76d111c8").then(next)
    },
  },
  {
    path: "/skill/js/regex/index.html",
    redirect: "/skill/js/regex/"
  },
  {
    name: "v-38525a10",
    path: "/skill/js/typescript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-38525a10").then(next)
    },
  },
  {
    path: "/skill/js/typescript/index.html",
    redirect: "/skill/js/typescript/"
  },
  {
    name: "v-63b65a5c",
    path: "/skill/nodejs/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-63b65a5c").then(next)
    },
  },
  {
    path: "/skill/nodejs/index.html",
    redirect: "/skill/nodejs/"
  },
  {
    name: "v-cb059bc8",
    path: "/skill/nodejs/koa/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cb059bc8").then(next)
    },
  },
  {
    path: "/skill/nodejs/koa/index.html",
    redirect: "/skill/nodejs/koa/"
  },
  {
    name: "v-826e4d48",
    path: "/skill/nodejs/multi-process/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-826e4d48").then(next)
    },
  },
  {
    path: "/skill/nodejs/multi-process/index.html",
    redirect: "/skill/nodejs/multi-process/"
  },
  {
    name: "v-4e427f70",
    path: "/skill/nodejs/node-mysql/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4e427f70").then(next)
    },
  },
  {
    path: "/skill/nodejs/node-mysql/index.html",
    redirect: "/skill/nodejs/node-mysql/"
  },
  {
    name: "v-49d96988",
    path: "/skill/nodejs/other/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-49d96988").then(next)
    },
  },
  {
    path: "/skill/nodejs/other/index.html",
    redirect: "/skill/nodejs/other/"
  },
  {
    name: "v-336f6b08",
    path: "/skill/note/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-336f6b08").then(next)
    },
  },
  {
    path: "/skill/note/index.html",
    redirect: "/skill/note/"
  },
  {
    name: "v-2c9655bc",
    path: "/skill/note/d2-2019/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2c9655bc").then(next)
    },
  },
  {
    path: "/skill/note/d2-2019/index.html",
    redirect: "/skill/note/d2-2019/"
  },
  {
    name: "v-21811ba2",
    path: "/skill/note/hooks-vs-class/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-21811ba2").then(next)
    },
  },
  {
    path: "/skill/note/hooks-vs-class/index.html",
    redirect: "/skill/note/hooks-vs-class/"
  },
  {
    name: "v-604493fc",
    path: "/skill/note/links/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-604493fc").then(next)
    },
  },
  {
    path: "/skill/note/links/index.html",
    redirect: "/skill/note/links/"
  },
  {
    name: "v-56a23488",
    path: "/skill/note/react-deep-learning/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-56a23488").then(next)
    },
  },
  {
    path: "/skill/note/react-deep-learning/index.html",
    redirect: "/skill/note/react-deep-learning/"
  },
  {
    name: "v-19e51fbc",
    path: "/skill/note/vue-conf-2018/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-19e51fbc").then(next)
    },
  },
  {
    path: "/skill/note/vue-conf-2018/index.html",
    redirect: "/skill/note/vue-conf-2018/"
  },
  {
    name: "v-45c21148",
    path: "/skill/note/vue-conf-2018/author-speech/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-45c21148").then(next)
    },
  },
  {
    path: "/skill/note/vue-conf-2018/author-speech/index.html",
    redirect: "/skill/note/vue-conf-2018/author-speech/"
  },
  {
    name: "v-00429888",
    path: "/skill/note/vue-conf-2018/maintaining-vue-cli/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-00429888").then(next)
    },
  },
  {
    path: "/skill/note/vue-conf-2018/maintaining-vue-cli/index.html",
    redirect: "/skill/note/vue-conf-2018/maintaining-vue-cli/"
  },
  {
    name: "v-69c821b4",
    path: "/skill/note/vue-conf-2018/my-feeling/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-69c821b4").then(next)
    },
  },
  {
    path: "/skill/note/vue-conf-2018/my-feeling/index.html",
    redirect: "/skill/note/vue-conf-2018/my-feeling/"
  },
  {
    name: "v-2fba2a3c",
    path: "/skill/note/vue-conf-2018/vue-declarative/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2fba2a3c").then(next)
    },
  },
  {
    path: "/skill/note/vue-conf-2018/vue-declarative/index.html",
    redirect: "/skill/note/vue-conf-2018/vue-declarative/"
  },
  {
    name: "v-4696745c",
    path: "/skill/note/webpack5/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4696745c").then(next)
    },
  },
  {
    path: "/skill/note/webpack5/index.html",
    redirect: "/skill/note/webpack5/"
  },
  {
    name: "v-4fd7a6bc",
    path: "/skill/personal/2020-q3/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4fd7a6bc").then(next)
    },
  },
  {
    path: "/skill/personal/2020-q3/index.html",
    redirect: "/skill/personal/2020-q3/"
  },
  {
    name: "v-65c0de3c",
    path: "/skill/personal/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-65c0de3c").then(next)
    },
  },
  {
    path: "/skill/personal/index.html",
    redirect: "/skill/personal/"
  },
  {
    name: "v-75c021f4",
    path: "/skill/project/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-75c021f4").then(next)
    },
  },
  {
    path: "/skill/project/index.html",
    redirect: "/skill/project/"
  },
  {
    name: "v-0ada1d84",
    path: "/skill/project/babel/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0ada1d84").then(next)
    },
  },
  {
    path: "/skill/project/babel/index.html",
    redirect: "/skill/project/babel/"
  },
  {
    name: "v-61f4a56c",
    path: "/skill/project/charles/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-61f4a56c").then(next)
    },
  },
  {
    path: "/skill/project/charles/index.html",
    redirect: "/skill/project/charles/"
  },
  {
    name: "v-3e2fb1cf",
    path: "/skill/project/chrome-extension/DEMO.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3e2fb1cf").then(next)
    },
  },
  {
    name: "v-445829fc",
    path: "/skill/project/chrome-extension/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-445829fc").then(next)
    },
  },
  {
    path: "/skill/project/chrome-extension/index.html",
    redirect: "/skill/project/chrome-extension/"
  },
  {
    name: "v-7a3eea7c",
    path: "/skill/project/ci-cd/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7a3eea7c").then(next)
    },
  },
  {
    path: "/skill/project/ci-cd/index.html",
    redirect: "/skill/project/ci-cd/"
  },
  {
    name: "v-38c1e332",
    path: "/skill/project/compatibility/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-38c1e332").then(next)
    },
  },
  {
    path: "/skill/project/compatibility/index.html",
    redirect: "/skill/project/compatibility/"
  },
  {
    name: "v-6bace5fc",
    path: "/skill/project/compatibility/h5/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6bace5fc").then(next)
    },
  },
  {
    path: "/skill/project/compatibility/h5/index.html",
    redirect: "/skill/project/compatibility/h5/"
  },
  {
    name: "v-348427de",
    path: "/skill/project/compatibility/h5/MEDIA.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-348427de").then(next)
    },
  },
  {
    name: "v-965b8988",
    path: "/skill/project/compatibility/pc/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-965b8988").then(next)
    },
  },
  {
    path: "/skill/project/compatibility/pc/index.html",
    redirect: "/skill/project/compatibility/pc/"
  },
  {
    name: "v-0f9a861c",
    path: "/skill/project/mp/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0f9a861c").then(next)
    },
  },
  {
    path: "/skill/project/mp/index.html",
    redirect: "/skill/project/mp/"
  },
  {
    name: "v-28393b90",
    path: "/skill/project/notes/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-28393b90").then(next)
    },
  },
  {
    path: "/skill/project/notes/index.html",
    redirect: "/skill/project/notes/"
  },
  {
    name: "v-453acde2",
    path: "/skill/project/notes/SaveAsZip.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-453acde2").then(next)
    },
  },
  {
    name: "v-a59d45c0",
    path: "/skill/project/notes/bot/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a59d45c0").then(next)
    },
  },
  {
    path: "/skill/project/notes/bot/index.html",
    redirect: "/skill/project/notes/bot/"
  },
  {
    name: "v-1d77c51c",
    path: "/skill/project/notes/mini-diary/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1d77c51c").then(next)
    },
  },
  {
    path: "/skill/project/notes/mini-diary/index.html",
    redirect: "/skill/project/notes/mini-diary/"
  },
  {
    name: "v-ffd4d2c8",
    path: "/skill/project/notes/official-website/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ffd4d2c8").then(next)
    },
  },
  {
    path: "/skill/project/notes/official-website/index.html",
    redirect: "/skill/project/notes/official-website/"
  },
  {
    name: "v-76bd6988",
    path: "/skill/project/npm/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-76bd6988").then(next)
    },
  },
  {
    path: "/skill/project/npm/index.html",
    redirect: "/skill/project/npm/"
  },
  {
    name: "v-43f5ab46",
    path: "/skill/project/package/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-43f5ab46").then(next)
    },
  },
  {
    path: "/skill/project/package/index.html",
    redirect: "/skill/project/package/"
  },
  {
    name: "v-da2bcec8",
    path: "/skill/project/prettier-vue-cli/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-da2bcec8").then(next)
    },
  },
  {
    path: "/skill/project/prettier-vue-cli/index.html",
    redirect: "/skill/project/prettier-vue-cli/"
  },
  {
    name: "v-4ddf7a88",
    path: "/skill/project/react-project-note/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4ddf7a88").then(next)
    },
  },
  {
    path: "/skill/project/react-project-note/index.html",
    redirect: "/skill/project/react-project-note/"
  },
  {
    name: "v-4efe777c",
    path: "/skill/project/source-map/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4efe777c").then(next)
    },
  },
  {
    path: "/skill/project/source-map/index.html",
    redirect: "/skill/project/source-map/"
  },
  {
    name: "v-58783e49",
    path: "/skill/project/webpack/DEMO.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-58783e49").then(next)
    },
  },
  {
    name: "v-6969e328",
    path: "/skill/react/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6969e328").then(next)
    },
  },
  {
    path: "/skill/react/index.html",
    redirect: "/skill/react/"
  },
  {
    name: "v-6e89cb8e",
    path: "/skill/react/error-usage/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e89cb8e").then(next)
    },
  },
  {
    path: "/skill/react/error-usage/index.html",
    redirect: "/skill/react/error-usage/"
  },
  {
    name: "v-e78a9aa4",
    path: "/skill/react/fiber/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e78a9aa4").then(next)
    },
  },
  {
    path: "/skill/react/fiber/index.html",
    redirect: "/skill/react/fiber/"
  },
  {
    name: "v-2b14aa9c",
    path: "/skill/react/life-cycle/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2b14aa9c").then(next)
    },
  },
  {
    path: "/skill/react/life-cycle/index.html",
    redirect: "/skill/react/life-cycle/"
  },
  {
    name: "v-1ad81c9c",
    path: "/skill/react/optimize/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1ad81c9c").then(next)
    },
  },
  {
    path: "/skill/react/optimize/index.html",
    redirect: "/skill/react/optimize/"
  },
  {
    name: "v-45ebc04e",
    path: "/skill/react/react-composition/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-45ebc04e").then(next)
    },
  },
  {
    path: "/skill/react/react-composition/index.html",
    redirect: "/skill/react/react-composition/"
  },
  {
    name: "v-6e9c1a7e",
    path: "/skill/react/react-ssr/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e9c1a7e").then(next)
    },
  },
  {
    path: "/skill/react/react-ssr/index.html",
    redirect: "/skill/react/react-ssr/"
  },
  {
    name: "v-2cd626c4",
    path: "/skill/react/redux/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2cd626c4").then(next)
    },
  },
  {
    path: "/skill/react/redux/index.html",
    redirect: "/skill/react/redux/"
  },
  {
    name: "v-3ca3adba",
    path: "/skill/react/set-state/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3ca3adba").then(next)
    },
  },
  {
    path: "/skill/react/set-state/index.html",
    redirect: "/skill/react/set-state/"
  },
  {
    name: "v-a9b52548",
    path: "/skill/react/souce-code/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a9b52548").then(next)
    },
  },
  {
    path: "/skill/react/souce-code/index.html",
    redirect: "/skill/react/souce-code/"
  },
  {
    name: "v-87399e4c",
    path: "/skill/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-87399e4c").then(next)
    },
  },
  {
    path: "/skill/vue/index.html",
    redirect: "/skill/vue/"
  },
  {
    name: "v-1c2a189c",
    path: "/skill/react/standard/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c2a189c").then(next)
    },
  },
  {
    path: "/skill/react/standard/index.html",
    redirect: "/skill/react/standard/"
  },
  {
    name: "v-55a30648",
    path: "/skill/vue/build/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-55a30648").then(next)
    },
  },
  {
    path: "/skill/vue/build/index.html",
    redirect: "/skill/vue/build/"
  },
  {
    name: "v-6830fd48",
    path: "/skill/vue/basic/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6830fd48").then(next)
    },
  },
  {
    path: "/skill/vue/basic/index.html",
    redirect: "/skill/vue/basic/"
  },
  {
    name: "v-12403864",
    path: "/skill/vue/component-lib/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-12403864").then(next)
    },
  },
  {
    path: "/skill/vue/component-lib/index.html",
    redirect: "/skill/vue/component-lib/"
  },
  {
    name: "v-52c954be",
    path: "/skill/vue/component/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-52c954be").then(next)
    },
  },
  {
    path: "/skill/vue/component/index.html",
    redirect: "/skill/vue/component/"
  },
  {
    name: "v-483a77ac",
    path: "/skill/vue/data-driven/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-483a77ac").then(next)
    },
  },
  {
    path: "/skill/vue/data-driven/index.html",
    redirect: "/skill/vue/data-driven/"
  },
  {
    name: "v-6e544a9c",
    path: "/skill/vue/feature-v3/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e544a9c").then(next)
    },
  },
  {
    path: "/skill/vue/feature-v3/index.html",
    redirect: "/skill/vue/feature-v3/"
  },
  {
    name: "v-d06a7e88",
    path: "/skill/vue/keep-alive/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d06a7e88").then(next)
    },
  },
  {
    path: "/skill/vue/keep-alive/index.html",
    redirect: "/skill/vue/keep-alive/"
  },
  {
    name: "v-73e729ba",
    path: "/skill/vue/key/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-73e729ba").then(next)
    },
  },
  {
    path: "/skill/vue/key/index.html",
    redirect: "/skill/vue/key/"
  },
  {
    name: "v-4fb74abc",
    path: "/skill/vue/life-cycle/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4fb74abc").then(next)
    },
  },
  {
    path: "/skill/vue/life-cycle/index.html",
    redirect: "/skill/vue/life-cycle/"
  },
  {
    name: "v-7cf8745c",
    path: "/skill/vue/question/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7cf8745c").then(next)
    },
  },
  {
    path: "/skill/vue/question/index.html",
    redirect: "/skill/vue/question/"
  },
  {
    name: "v-11aaf21c",
    path: "/skill/vue/vue-router/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-11aaf21c").then(next)
    },
  },
  {
    path: "/skill/vue/vue-router/index.html",
    redirect: "/skill/vue/vue-router/"
  },
  {
    name: "v-fc8b9884",
    path: "/skill/web/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fc8b9884").then(next)
    },
  },
  {
    path: "/skill/web/index.html",
    redirect: "/skill/web/"
  },
  {
    name: "v-1741733c",
    path: "/skill/web/http-cache/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1741733c").then(next)
    },
  },
  {
    path: "/skill/web/http-cache/index.html",
    redirect: "/skill/web/http-cache/"
  },
  {
    name: "v-0be2cc4c",
    path: "/skill/web/browser/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0be2cc4c").then(next)
    },
  },
  {
    path: "/skill/web/browser/index.html",
    redirect: "/skill/web/browser/"
  },
  {
    name: "v-083f8588",
    path: "/skill/web/cors/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-083f8588").then(next)
    },
  },
  {
    path: "/skill/web/cors/index.html",
    redirect: "/skill/web/cors/"
  },
  {
    name: "v-289f68fc",
    path: "/skill/web/cdn/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-289f68fc").then(next)
    },
  },
  {
    path: "/skill/web/cdn/index.html",
    redirect: "/skill/web/cdn/"
  },
  {
    name: "v-03c6acdc",
    path: "/skill/web/http/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-03c6acdc").then(next)
    },
  },
  {
    path: "/skill/web/http/index.html",
    redirect: "/skill/web/http/"
  },
  {
    name: "v-dbc29608",
    path: "/skill/web/other/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dbc29608").then(next)
    },
  },
  {
    path: "/skill/web/other/index.html",
    redirect: "/skill/web/other/"
  },
  {
    name: "v-5bed87f8",
    path: "/skill/web/ssr/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5bed87f8").then(next)
    },
  },
  {
    path: "/skill/web/ssr/index.html",
    redirect: "/skill/web/ssr/"
  },
  {
    name: "v-f871fb08",
    path: "/skill/web/web-attack/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f871fb08").then(next)
    },
  },
  {
    path: "/skill/web/web-attack/index.html",
    redirect: "/skill/web/web-attack/"
  },
  {
    name: "v-ff3d03d0",
    path: "/skill/web/web-storage/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ff3d03d0").then(next)
    },
  },
  {
    path: "/skill/web/web-storage/index.html",
    redirect: "/skill/web/web-storage/"
  },
  {
    name: "v-00513a5c",
    path: "/skill/web/web-vitals/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-00513a5c").then(next)
    },
  },
  {
    path: "/skill/web/web-vitals/index.html",
    redirect: "/skill/web/web-vitals/"
  },
  {
    name: "v-3b86099a",
    path: "/skill/web/websocket/DEMO.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b86099a").then(next)
    },
  },
  {
    name: "v-cfd3b2e4",
    path: "/skill/web/websocket/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cfd3b2e4").then(next)
    },
  },
  {
    path: "/skill/web/websocket/index.html",
    redirect: "/skill/web/websocket/"
  },
  {
    name: "v-a6205f88",
    path: "/tool/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a6205f88").then(next)
    },
  },
  {
    path: "/tool/index.html",
    redirect: "/tool/"
  },
  {
    name: "v-13c50548",
    path: "/tool/airpods/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-13c50548").then(next)
    },
  },
  {
    path: "/tool/airpods/index.html",
    redirect: "/tool/airpods/"
  },
  {
    name: "v-1670f6dc",
    path: "/tool/charles/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1670f6dc").then(next)
    },
  },
  {
    path: "/tool/charles/index.html",
    redirect: "/tool/charles/"
  },
  {
    name: "v-53567d9c",
    path: "/tool/cmd/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-53567d9c").then(next)
    },
  },
  {
    path: "/tool/cmd/index.html",
    redirect: "/tool/cmd/"
  },
  {
    name: "v-5a3c465c",
    path: "/tool/http-server/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5a3c465c").then(next)
    },
  },
  {
    path: "/tool/http-server/index.html",
    redirect: "/tool/http-server/"
  },
  {
    name: "v-c4b68208",
    path: "/tool/paste/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c4b68208").then(next)
    },
  },
  {
    path: "/tool/paste/index.html",
    redirect: "/tool/paste/"
  },
  {
    name: "v-36b20d6c",
    path: "/tool/shell-script/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-36b20d6c").then(next)
    },
  },
  {
    path: "/tool/shell-script/index.html",
    redirect: "/tool/shell-script/"
  },
  {
    name: "v-3fc47f48",
    path: "/tool/vuepress-stat/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3fc47f48").then(next)
    },
  },
  {
    path: "/tool/vuepress-stat/index.html",
    redirect: "/tool/vuepress-stat/"
  },
  {
    name: "v-1127f008",
    path: "/tool/vuepress-zoom/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1127f008").then(next)
    },
  },
  {
    path: "/tool/vuepress-zoom/index.html",
    redirect: "/tool/vuepress-zoom/"
  },
  {
    name: "v-05f5001d",
    path: "/output/fruit/template/DEMO.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-05f5001d").then(next)
    },
  },
  {
    name: "v-ef4fdb22",
    path: "/skill/algorithm/sort/Sort.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ef4fdb22").then(next)
    },
  },
  {
    name: "v-181a069e",
    path: "/skill/css/other/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-181a069e").then(next)
    },
  },
  {
    path: "/skill/css/other/index.html",
    redirect: "/skill/css/other/"
  },
  {
    name: "v-3fbd0366",
    path: "/skill/js/async-plan/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3fbd0366").then(next)
    },
  },
  {
    path: "/skill/js/async-plan/index.html",
    redirect: "/skill/js/async-plan/"
  },
  {
    name: "v-59de06d0",
    path: "/skill/note/complete-intro-react/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-59de06d0").then(next)
    },
  },
  {
    path: "/skill/note/complete-intro-react/index.html",
    redirect: "/skill/note/complete-intro-react/"
  },
  {
    name: "v-d0802ac8",
    path: "/skill/note/vue-composition-api-rfc/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d0802ac8").then(next)
    },
  },
  {
    path: "/skill/note/vue-composition-api-rfc/index.html",
    redirect: "/skill/note/vue-composition-api-rfc/"
  },
  {
    name: "v-3afc9af2",
    path: "/skill/project/other/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3afc9af2").then(next)
    },
  },
  {
    path: "/skill/project/other/index.html",
    redirect: "/skill/project/other/"
  },
  {
    name: "v-12c8c688",
    path: "/skill/project/rollup/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-12c8c688").then(next)
    },
  },
  {
    path: "/skill/project/rollup/index.html",
    redirect: "/skill/project/rollup/"
  },
  {
    name: "v-476df2b8",
    path: "/skill/project/webpack/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-476df2b8").then(next)
    },
  },
  {
    path: "/skill/project/webpack/index.html",
    redirect: "/skill/project/webpack/"
  },
  {
    name: "v-130a88ac",
    path: "/skill/react/basic/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-130a88ac").then(next)
    },
  },
  {
    path: "/skill/react/basic/index.html",
    redirect: "/skill/react/basic/"
  },
  {
    name: "v-69858f3e",
    path: "/skill/react/feature-v16/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-69858f3e").then(next)
    },
  },
  {
    path: "/skill/react/feature-v16/index.html",
    redirect: "/skill/react/feature-v16/"
  },
  {
    name: "v-5a2d53bc",
    path: "/skill/web/optimize/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5a2d53bc").then(next)
    },
  },
  {
    path: "/skill/web/optimize/index.html",
    redirect: "/skill/web/optimize/"
  },
  {
    name: "v-a9ab20d0",
    path: "/skill/note/webpack-experience/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a9ab20d0").then(next)
    },
  },
  {
    path: "/skill/note/webpack-experience/index.html",
    redirect: "/skill/note/webpack-experience/"
  },
  {
    name: "v-65e17c26",
    path: "/skill/react/hooks/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-65e17c26").then(next)
    },
  },
  {
    path: "/skill/react/hooks/index.html",
    redirect: "/skill/react/hooks/"
  },
  {
    name: "v-5c62eb88",
    path: "/skill/web/diff/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5c62eb88").then(next)
    },
  },
  {
    path: "/skill/web/diff/index.html",
    redirect: "/skill/web/diff/"
  },
  {
    name: "v-5d19f6fc",
    path: "/skill/js/other/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5d19f6fc").then(next)
    },
  },
  {
    path: "/skill/js/other/index.html",
    redirect: "/skill/js/other/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]